In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
# Load a non-stationary dataset
df = pd.read_csv('tempandq2.csv',index_col='date',parse_dates=True)
df.index.freq = "D" #오름차순으로 읽어들여야함

In [3]:
df.head()

q
date              
2019-01-01   9.063
2019-01-02   9.104
2019-01-03   3.198
2019-01-04   3.493
2019-01-05  14.994

In [4]:
from distutils.version import LooseVersion
from packaging import version

In [5]:
len(df) #2019-2021

1096

In [7]:
train = df.iloc[:1000]
test = df.iloc[1000:]

In [8]:
from sklearn.preprocessing import MinMaxScaler

C:\Users\min\anaconda3\envs\tsa_course\lib\site-packages\sklearn\utils\validation.py:37: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  LARGE_SPARSE_SUPPORTED = LooseVersion(scipy_version) >= '0.14.0'


In [9]:
scaler = MinMaxScaler()

In [11]:
train=scaler.fit_transform(train)

In [12]:
test=scaler.fit_transform(test)

In [14]:
print(train)

[[2.68681407e-03]
 [2.69896891e-03]
 [9.48078052e-04]
 [1.03553366e-03]
 [4.44511642e-03]
 [9.49263891e-04]
 [2.69778307e-03]
 [2.70015475e-03]
 [9.48967431e-04]
 [9.56082463e-04]
 [2.71883171e-03]
 [2.70489811e-03]
 [2.70074767e-03]
 [9.63790415e-04]
 [2.69303972e-03]
 [9.42148858e-04]
 [2.69867245e-03]
 [2.69244680e-03]
 [9.54896625e-04]
 [9.68237310e-04]
 [4.43978015e-03]
 [9.64086875e-04]
 [2.69778307e-03]
 [2.79116787e-03]
 [9.65569173e-04]
 [2.70134059e-03]
 [9.70312528e-04]
 [2.71112376e-03]
 [9.79799238e-04]
 [9.64086875e-04]
 [2.71557066e-03]
 [9.78316939e-04]
 [2.71023438e-03]
 [4.44185536e-03]
 [4.44126244e-03]
 [2.71438482e-03]
 [2.70489811e-03]
 [4.43622263e-03]
 [2.71408836e-03]
 [9.69719608e-04]
 [9.83356754e-04]
 [2.71497774e-03]
 [2.71764587e-03]
 [9.73277125e-04]
 [9.86617810e-04]
 [2.72090693e-03]
 [9.85431971e-04]
 [9.75055883e-04]
 [2.70460165e-03]
 [2.70726978e-03]
 [2.72120339e-03]
 [2.71171668e-03]
 [9.89878867e-04]
 [2.71912817e-03]
 [2.72090693e-03]
 [9.958080

In [15]:
from keras.preprocessing.sequence import TimeseriesGenerator

In [31]:
n_input = 365
n_features=1
generator = TimeseriesGenerator(train, train, length=n_input, batch_size=1)

In [18]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

In [32]:
model = Sequential()
model.add(LSTM(150, activation='relu', input_shape=(n_input, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [33]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_1 (LSTM)               (None, 150)               91200     
                                                                 
 dense_1 (Dense)             (None, 1)                 151       
                                                                 
Total params: 91,351
Trainable params: 91,351
Non-trainable params: 0
_________________________________________________________________


In [35]:
# fit model
model.fit_generator(generator,epochs=30)

Epoch 1/30
  2/635 [..............................] - ETA: 32s - loss: 2.4461e-04

C:\Users\min\anaconda3\envs\tsa_course\lib\site-packages\ipykernel_launcher.py:2: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  


635/635 [==============================] - 33s 52ms/step - loss: 0.0040
Epoch 2/30
635/635 [==============================] - 33s 52ms/step - loss: 0.0035
Epoch 3/30
635/635 [==============================] - 33s 52ms/step - loss: 0.0036
Epoch 4/30
635/635 [==============================] - 33s 52ms/step - loss: 0.0034
Epoch 5/30
635/635 [==============================] - 33s 52ms/step - loss: 0.0034
Epoch 6/30
635/635 [==============================] - 33s 52ms/step - loss: 0.0034
Epoch 7/30
635/635 [==============================] - 33s 52ms/step - loss: 0.0032
Epoch 8/30
635/635 [==============================] - 33s 53ms/step - loss: 0.0031
Epoch 9/30
478/635 [=====================>........] - ETA: 8s - loss: 0.0040

KeyboardInterrupt: 

In [36]:
model.history.history.keys()

dict_keys(['loss'])

In [38]:
first_eval_batch = train[-365:]

In [39]:
first_eval_batch

array([[2.38353582e-02],
       [1.68015558e-02],
       [1.33777430e-02],
       [1.30222878e-02],
       [1.26881778e-02],
       [1.27204919e-02],
       [1.08702870e-02],
       [9.02660429e-03],
       [9.07581660e-03],
       [6.90721405e-03],
       [6.93715648e-03],
       [6.96680245e-03],
       [3.27943696e-03],
       [7.02312978e-03],
       [5.20286736e-03],
       [5.23458854e-03],
       [5.26660619e-03],
       [5.29625216e-03],
       [3.49763129e-03],
       [3.53557813e-03],
       [3.57293205e-03],
       [5.43380945e-03],
       [3.63904255e-03],
       [5.50673853e-03],
       [3.46709594e-03],
       [3.48666228e-03],
       [3.54387900e-03],
       [1.75919173e-03],
       [3.62777709e-03],
       [3.67046728e-03],
       [1.89704548e-03],
       [1.94358965e-03],
       [3.79142283e-03],
       [2.03549215e-03],
       [2.08351862e-03],
       [1.62637780e-03],
       [3.46917116e-03],
       [1.71620508e-03],
       [1.77490410e-03],
       [1.82559870e-03],


In [48]:
test_predictions = []

first_eval_batch = train[-n_input:]
current_batch = first_eval_batch.reshape((1, n_input, n_features))

for i in range(len(test)):
    
    # get prediction 1 time stamp ahead ([0] is for grabbing just the number instead of [array])
    current_pred = model.predict(current_batch)[0]
    
    # store prediction
    test_predictions.append(current_pred) 
    
    # update batch to now include prediction and drop first value
    current_batch = np.append(current_batch[:,1:,:],[[current_pred]],axis=1)

1/1 [==============================] - 0s 24ms/step


In [49]:
true_predictions = scaler.inverse_transform(test_predictions)

In [52]:
true_predictions

array([[2.21596009],
       [2.23653361],
       [2.24869325],
       [2.25597528],
       [2.26034668],
       [2.26298097],
       [2.26457656],
       [2.26555009],
       [2.2661496 ],
       [2.26652331],
       [2.26675938],
       [2.26691085],
       [2.26701007],
       [2.26707617],
       [2.26712096],
       [2.26715206],
       [2.26717399],
       [2.26718969],
       [2.26720105],
       [2.2672096 ],
       [2.26721567],
       [2.26722033],
       [2.26722375],
       [2.2672264 ],
       [2.26722826],
       [2.26722966],
       [2.26723075],
       [2.26723153],
       [2.26723215],
       [2.26723262],
       [2.26723293],
       [2.26723308],
       [2.26723324],
       [2.26723339],
       [2.26723339],
       [2.26723339],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.26723355],
       [2.267

In [53]:
test['Predictions'] = true_predictions

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [54]:
test.plot(figsize=(12,8))

AttributeError: 'numpy.ndarray' object has no attribute 'plot'

In [58]:
plt.scatter(test[:1])

TypeError: scatter() missing 1 required positional argument: 'y'