In [29]:
import numpy as np
import pandas as pd

df2=pd.read_csv('soyang3.csv',index_col=0, header=0)
df1=pd.read_csv('soyangpre.csv',index_col=0, header=0)

In [30]:
print(kospi200)
print(samsung)
print(kospi200.shape)
print(samsung.shape)

[[1.000e+00 9.063e+00]
 [2.000e+00 9.104e+00]
 [3.000e+00 3.198e+00]
 ...
 [1.094e+03 6.961e+00]
 [1.095e+03 6.997e+00]
 [1.096e+03 7.022e+00]]
[[1.000e+00 0.000e+00]
 [2.000e+00 0.000e+00]
 [3.000e+00 0.000e+00]
 ...
 [1.094e+03 2.000e-01]
 [1.095e+03 0.000e+00]
 [1.096e+03 0.000e+00]]
(1096, 2)
(1096, 2)


In [31]:
df1 = df1.values
df2 = df2.values

In [32]:
np.save('kospi200.npy', arr=df1)
np.save('samsung.npy', arr=df2)

In [34]:
import numpy as np
import pandas as pd

kospi200 = np.load('kospi200.npy',allow_pickle=True)
samsung = np.load('samsung.npy',allow_pickle=True)

print(kospi200)
print(samsung)
print(kospi200.shape)
print(samsung.shape)

[[1.000e+00 0.000e+00]
 [2.000e+00 0.000e+00]
 [3.000e+00 0.000e+00]
 ...
 [1.094e+03 2.000e-01]
 [1.095e+03 0.000e+00]
 [1.096e+03 0.000e+00]]
[[1.000e+00 9.063e+00]
 [2.000e+00 9.104e+00]
 [3.000e+00 3.198e+00]
 ...
 [1.094e+03 6.961e+00]
 [1.095e+03 6.997e+00]
 [1.096e+03 7.022e+00]]
(1096, 2)
(1096, 2)


In [33]:
def split_xy5(dataset, time_steps, y_column):
    x, y = list(), list()
    for i in range(len(dataset)):
        x_end_number = i + time_steps
        y_end_number = x_end_number + y_column # 수정

        if y_end_number > len(dataset):  # 수정
            break
        tmp_x = dataset[i:x_end_number, :]  # 수정
        tmp_y = dataset[x_end_number:y_end_number, 1]    # 수정
        x.append(tmp_x)
        y.append(tmp_y)
    return np.array(x), np.array(y)
x, y = split_xy5(samsung, 5, 1) 
print(x[0,:], "\n", y[0])
print(x.shape)
print(y.shape)

[[1. 0.]
 [2. 0.]
 [3. 0.]
 [4. 0.]
 [5. 0.]] 
 [0.]
(1091, 5, 2)
(1091, 1)


In [35]:
from sklearn.model_selection import train_test_split
# from sklearn.model_selection import cross_val_score
x_train, x_test, y_train, y_test = train_test_split(
    x, y, random_state=1, test_size = 0.3)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)
#70%

(763, 5, 2)
(328, 5, 2)
(763, 1)
(328, 1)


In [36]:
x_train = np.reshape(x_train,
    (x_train.shape[0], x_train.shape[1] * x_train.shape[2]))
x_test = np.reshape(x_test,
    (x_test.shape[0], x_test.shape[1] * x_test.shape[2]))
print(x_train.shape)
print(x_test.shape)


(763, 10)
(328, 10)


In [37]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)
print(x_train_scaled[0, :])

[ 0.18179804  0.18592649  0.18179804  0.80335571  0.18179804  0.70309619
  0.18179804  0.47137205  0.18179804 -0.32097932]


In [46]:
from keras.models import Sequential
from keras.layers import Dense

# 모델구성
model = Sequential()
model.add(Dense(64, input_shape=(10, )))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1))

In [47]:
model.compile(loss='mse', optimizer='adam', metrics=['mse'])

In [48]:
from keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(patience=20)
model.fit(x_train_scaled, y_train, verbose=1,
          batch_size=1, epochs=100, callbacks=[early_stopping])

loss, mse = model.evaluate(x_test_scaled, y_test, batch_size=1)
print('loss : ', loss)
print('mse : ', mse)

Epoch 1/100
763/763 [==============================] - 1s 661us/step - loss: 98.2203 - mse: 98.2203
Epoch 2/100
763/763 [==============================] - 0s 648us/step - loss: 97.1119 - mse: 97.1119
Epoch 3/100
763/763 [==============================] - 0s 650us/step - loss: 95.5720 - mse: 95.5720
Epoch 4/100
763/763 [==============================] - 0s 654us/step - loss: 95.0976 - mse: 95.0976
Epoch 5/100
763/763 [==============================] - 1s 660us/step - loss: 94.5248 - mse: 94.5248
Epoch 6/100
763/763 [==============================] - 1s 656us/step - loss: 97.1854 - mse: 97.1854
Epoch 7/100
763/763 [==============================] - 0s 654us/step - loss: 93.9050 - mse: 93.9050
Epoch 8/100
763/763 [==============================] - 1s 659us/step - loss: 94.5213 - mse: 94.5213
Epoch 9/100
763/763 [==============================] - 1s 655us/step - loss: 93.9386 - mse: 93.9386
Epoch 10/100
763/763 [==============================] - 1s 664us/step - loss: 92.8664 - mse: 92.8664

Epoch 28/100
763/763 [==============================] - 1s 672us/step - loss: 86.1662 - mse: 86.1662
Epoch 29/100
763/763 [==============================] - 1s 658us/step - loss: 78.8227 - mse: 78.8227
Epoch 30/100
763/763 [==============================] - 0s 651us/step - loss: 75.5391 - mse: 75.5391
Epoch 31/100
763/763 [==============================] - 0s 647us/step - loss: 76.1290 - mse: 76.1290
Epoch 32/100
763/763 [==============================] - 1s 655us/step - loss: 77.1326 - mse: 77.1326
Epoch 33/100
763/763 [==============================] - 0s 651us/step - loss: 74.2281 - mse: 74.2281
Epoch 34/100
763/763 [==============================] - 1s 663us/step - loss: 71.3282 - mse: 71.3282
Epoch 35/100
763/763 [==============================] - 0s 643us/step - loss: 77.7771 - mse: 77.7771
Epoch 36/100
763/763 [==============================] - 0s 654us/step - loss: 75.9871 - mse: 75.9871
Epoch 37/100
763/763 [==============================] - 1s 663us/step - loss: 70.9054 - mse

Epoch 55/100
763/763 [==============================] - 0s 648us/step - loss: 64.3075 - mse: 64.3075
Epoch 56/100
763/763 [==============================] - 0s 654us/step - loss: 67.4307 - mse: 67.4307
Epoch 57/100
763/763 [==============================] - 0s 648us/step - loss: 66.9173 - mse: 66.9173
Epoch 58/100
763/763 [==============================] - 0s 650us/step - loss: 65.9161 - mse: 65.9161
Epoch 59/100
763/763 [==============================] - 0s 647us/step - loss: 63.9199 - mse: 63.9199
Epoch 60/100
763/763 [==============================] - 0s 639us/step - loss: 67.4548 - mse: 67.4548
Epoch 61/100
763/763 [==============================] - 0s 649us/step - loss: 66.9110 - mse: 66.9110
Epoch 62/100
763/763 [==============================] - 0s 646us/step - loss: 64.3252 - mse: 64.3252
Epoch 63/100
763/763 [==============================] - 0s 642us/step - loss: 60.1208 - mse: 60.1208
Epoch 64/100
763/763 [==============================] - 0s 645us/step - loss: 66.2189 - mse

Epoch 82/100
763/763 [==============================] - 0s 654us/step - loss: 57.3708 - mse: 57.3708
Epoch 83/100
763/763 [==============================] - 0s 647us/step - loss: 56.9018 - mse: 56.9018
Epoch 84/100
763/763 [==============================] - 0s 652us/step - loss: 56.9149 - mse: 56.9149
Epoch 85/100
763/763 [==============================] - 0s 652us/step - loss: 58.3623 - mse: 58.3623
Epoch 86/100
763/763 [==============================] - 0s 651us/step - loss: 60.9619 - mse: 60.9619
Epoch 87/100
763/763 [==============================] - 0s 648us/step - loss: 59.4576 - mse: 59.4576
Epoch 88/100
763/763 [==============================] - 0s 650us/step - loss: 59.1141 - mse: 59.1141
Epoch 89/100
763/763 [==============================] - 0s 647us/step - loss: 53.1396 - mse: 53.1396
Epoch 90/100
763/763 [==============================] - 0s 654us/step - loss: 55.0507 - mse: 55.0507
Epoch 91/100
763/763 [==============================] - 0s 651us/step - loss: 53.9245 - mse

In [49]:
y_pred = model.predict(x_test_scaled)

for i in range(5):
    print('종가 : ', y_test[i], '/ 예측가 : ', y_pred[i])




11/11 [==============================] - 0s 700us/step
종가 :  [0.] / 예측가 :  [2.2622664]
종가 :  [0.] / 예측가 :  [0.31755108]
종가 :  [59.4] / 예측가 :  [12.244736]
종가 :  [5.2] / 예측가 :  [2.407345]
종가 :  [0.] / 예측가 :  [-0.22380763]
